version: "3.8"

services:
  mongo:
    image: mongo
    container_name: hotbag-mongo
    ports:
      - "27017:27017"
    volumes:
      - mongo-data:/data/db

  backend:
    build:
      context: ./backend
    container_name: hotbag-backend
    ports:
      - "3000:3000"
    depends_on:
      - mongo
    environment:
      - PORT=3000
      - MONGO_URI=mongodb://mongo:27017/hotbag
      - ADMIN_API_KEY=supersecurekey123
    volumes:
      - ./backend:/app

volumes:
  mongo-data:
